branch-defaults:
  master:
    environment: grants-dev
global:
  application_name: grants
  branch: null
  default_ec2_keyname: awsmum
  default_platform: Tomcat 7 Java 7
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
